version: "3.7"

services:
  frontend:
    container_name: vue-monitor
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
